name = "sportsfest-portal"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "sportsfest-db"
database_id = "4ff094cf-501a-42ab-b796-ff48dc3578eb"
